name: CD

on: [repository_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Output
        run: echo "Workflow on branch_b triggered"

